spring:
  application:
    name: horse-racing-api

  datasource:
    url: jdbc:postgresql://localhost:5433/racing_db
    username: racing_user
    password: racing_dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none        # Don't touch our existing schema!
    show-sql: false
    properties:
      hibernate:
        default_schema: racing
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  security:
    user:
      name: admin
      password: admin123    # Temporary - we'll replace with proper auth later

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.horseracing: DEBUG
    org.hibernate.SQL: WARN
